part/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from part import views

app_name = 'customer'

urlpatterns = [
    
]

service_ticket_app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('customer.urls')),
    path('', include('ticket.urls')),
    path('',include('upcoming.urls')),
    path('',include('part.urls')),
    path('', views.TodayView.as_view(), name='today'),
    path('accounts/login/', views.user_login, name='login'),
    path('schedule/',views.CalendarView.as_view(), name='schedule'),
    path('logged_out/',views.user_logout, name='user_logout'),
]

upcoming/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

app_name = 'upcoming'

urlpatterns = [
    path('upcoming/', views.UpcomingView.as_view(), name='upcoming'),
    path('new-post/', views.PostCreateView.as_view(), name='new_post'),
    path('post-detail/<pk>',views.PostDetailView.as_view(), name='post_detail'),
    path('post-delete/<pk>', views.PostDeleteView.as_view(), name="post_delete"),
]

upcoming/models.py
from django.urls.base import reverse
from accounts.models import AccountCompany
from django.db import models
import datetime
from django.db.models.fields import DateField

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=256)
    description = models.TextField(max_length=999)
    date = models.DateField(default=datetime.date.today)
    account = models.ForeignKey(AccountCompany, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse("upcoming:post_detail", kwargs={"pk": self.pk})
    
    

upcoming/views.py
from django.views.generic.edit import DeleteView
from upcoming.models import Post
from django.shortcuts import render
from service_ticket_app.utils import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, CreateView, DetailView, DeleteView
from django.urls import reverse_lazy
# Create your views here.
class UpcomingView(LoginRequiredMixin, TemplateView):
    template_name = 'upcoming/upcoming.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ticket_count'] = ticket_count(self.request)
        context['tech_ticket_count'] = tech_ticket_count(self.request)
        context['tickets'] = all_tickets(self.request)
        context['tech_tickets_calendar'] = tech_tickets(self.request)
        context['todays_tickets_count'] = todays_tickets_count(self.request)
        context['in_progress_count'] = in_progress_count(self.request)
        context['completed_today_tickets_count'] = completed_today_tickets_count(self.request)
        context['tech_todays_tickets_count'] = tech_todays_tickets_count(self.request)
        context['posts'] = posts(self.request)
        return context

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ('title','description', 'date')

    def form_valid(self, form):
        form.instance.account = self.request.user.accountuser.account
        return super(PostCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tech_ticket'] = tech_tickets(self.request)
        context['ticket_count'] = ticket_count(self.request)
        context['tech_ticket_count'] = tech_ticket_count(self.request)
        context['todays_tickets'] = todays_tickets(self.request)
        context['tech_todays_tickets'] = tech_todays_tickets(self.request)
        context['todays_tickets_count'] = todays_tickets_count(self.request)
        context['in_progress_count'] = in_progress_count(self.request)
        context['completed_today_tickets_count'] = completed_today_tickets_count(self.request)
        context['tech_todays_tickets_count'] = tech_todays_tickets_count(self.request)
        context['tech_completed_today_tickets_count'] = tech_completed_today_tickets_count(self.request)
        return context 

class PostDetailView(LoginRequiredMixin,DetailView):
    model = Post
    template_name = 'upcoming/post_detail.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tech_ticket'] = tech_tickets(self.request)
        context['ticket_count'] = ticket_count(self.request)
        context['tech_ticket_count'] = tech_ticket_count(self.request)
        context['todays_tickets'] = todays_tickets(self.request)
        context['tech_todays_tickets'] = tech_todays_tickets(self.request)
        context['todays_tickets_count'] = todays_tickets_count(self.request)
        context['in_progress_count'] = in_progress_count(self.request)
        context['completed_today_tickets_count'] = completed_today_tickets_count(self.request)
        context['tech_todays_tickets_count'] = tech_todays_tickets_count(self.request)
        context['tech_completed_today_tickets_count'] = tech_completed_today_tickets_count(self.request)
        return context 

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('upcoming:upcoming') 

upcoming/templates/upcoming/post_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<h1> Are you sure you want to delete {{ post.title }}?</h1>

<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-outline-danger" value="Delete">
    <a href="{% url 'upcoming:upcoming' %}" type='button' class='btn btn-outline-dark'>Cancel</a>
</form>

{% endblock %}

upcoming/templates/upcoming/post_detail.html
{% extends 'base.html' %}
{% block content %}
<div>
  <a href="{% url 'upcoming:upcoming' %}" type="button" class="btn btn-outline-blue btn-rounded btn-sm px-2">
    <i class="fas fa-arrow-left lt mt-0"></i>
  </a>

  <a href="{% url 'upcoming:post_delete' pk=post.id %}" type="button" class="btn btn-outline-danger btn-rounded btn-sm px-2">
      <i class="far fa-trash-alt mt-0"></i>
  </a>
</div>
<div class='jumbotron '>
    <div class="container">
        <h2 class="display-4 text-center">{{ post.title }}</h2>
        <hr class="">
        <p class="lead">{{ post.description }}</p>
        <hr class="my-4">
        <small>{{ post.date }}</small>
  </div>
</div>
{% endblock %}

upcoming/templates/upcoming/post_form.html
{% extends 'base.html'%}
{% load bootstrap4 %}
{% block content %}
    <h2>
{% if not form.instance.pk %}
        Add New Item
    {% elif user.accountuser.role == 'Admin' %}
        Admin Edit
{% endif %}
    </h2>
    <form method='POST'>
        {% csrf_token %}
        {% bootstrap_form form %}
        <input class='btn btn-outline-primary' type="submit" value='Save'>
    </form>
{% endblock %}

upcoming/templates/upcoming/upcoming.html
{% extends 'base.html' %}
{% block extrahead %}
{% load static %}
    <link href="{% static 'css/addons/fullcalendar.min.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
<h1 class='text-center'>Upcoming</h1>
<hr>
<div class="row justify-content-between mb-5">
  <div class='col-8'>
    <h4>Add future jobs, shipments, or any other reminders you need.</h4>
  </div>
  <div class='col-1'> 
    <a href="{% url 'upcoming:new_post' %}" type='button' class='btn btn-sm btn-rounded btn-outline-primary'><i class="fas fa-plus text-primary"></i></a>
    </a>
  </div>
</div>
<section class="mt-5">
  <div class="row">
    <div class="col-md-12">
      <div id="calendar2"></div>
    </div>
  </div>
</section>
{% block scripts %}
<script>
$(document).ready(function(){
  var today = new Date();
  $('#calendar2').fullCalendar({
      header: {
              left: 'prev,next today',
              center: 'title',
              right: 'listWeek,month'
      },
      defaultDate: today,
      defaultView: 'month',
      

      eventRender: function (eventObj, $el) {
          $el.popover({
              title: eventObj.title,
              content: eventObj.description,
              trigger: 'hover',
              placement: 'top',
              container: 'body'
          });
      },

      events: [
        {% for p in posts %}  
          {
              title: '{{ p.title }}',
              description: '{{ p.description }}',
              date: '{{ p.date }}',
              url: "{% url 'upcoming:post_detail' pk=p.id %}",
              allDay: true,
          },
        {% endfor %}
      ]
  });
});
</script>
{% endblock %}
{% endblock%}