customer/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from customer import views

app_name = 'customer_app'

urlpatterns = [
    
    # Customers
    path('customers/', views.CustomerListView.as_view(),name='customers'),
    path('add-customer/',views.CustomerCreateView.as_view(), name="add_customer"),
    path('delete-customer-<pk>/',views.CustomerDeleteView.as_view(), name='delete_customer'),
    path('edit-<pk>/', views.CustomerUpdateView.as_view(), name='edit_customer'),
    # Companies
    path('companies/', views.CompanyListView.as_view(),name='companies'),
    path('add-company/',views.CompanyCreateView.as_view(), name="add_company"),
    path('delete-company-<pk>/',views.CompanyDeleteView.as_view(), name='delete_company'),
    path('company-edit-<pk>/', views.CompanyUpdateView.as_view(), name='edit_company'),
    # Jobsites
    path('jobsites/', views.JobsiteListView.as_view(),name='jobsites'),
    path('add-jobsite/',views.JobsiteCreateView.as_view(), name="add_jobsite"),
    path('delete-jobsite-<pk>/',views.JobsiteDeleteView.as_view(), name='delete_jobsite'),
    path('jobsite-edit-<pk>/', views.JobsiteUpdateView.as_view(), name='edit_jobsite'),
]

part/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from part import views

app_name = 'customer'

urlpatterns = [
    
]

service_ticket_app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('customer.urls')),
    path('', include('ticket.urls')),
    path('',include('upcoming.urls')),
    path('',include('part.urls')),
    path('', views.TodayView.as_view(), name='today'),
    path('accounts/login/', views.user_login, name='login'),
    path('schedule/',views.CalendarView.as_view(), name='schedule'),
    path('logged_out/',views.user_logout, name='user_logout'),
]

customer/models.py
from accounts.models import AccountCompany
from django.db import models
from django.urls import reverse
from phone_field import PhoneField

# Create your models here.

class Company(models.Model):
    name = models.CharField(max_length=100)
    address1 = models.CharField(max_length=100)
    address2 = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=2)
    zip_code = models.PositiveIntegerField()
    account = models.ForeignKey(AccountCompany, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("customer_app:companies")
    


class Customer(models.Model):
    fname = models.CharField(max_length=50)
    lname = models.CharField(max_length=50)
    email = models.EmailField()
    phone_number = PhoneField()
    company = models.ForeignKey(Company,null=True, on_delete=models.SET_NULL)
    note = models.TextField()
    account = models.ForeignKey(AccountCompany, on_delete=models.CASCADE)
    

    def __str__(self):
        return self.fname + ' ' + self.lname + ' - ' + str(self.company)

    def get_absolute_url(self):
        return reverse("customer_app:customers")
    

class Jobsite(models.Model):
    address1 = models.CharField(max_length=100)
    address2 = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=2)
    zip_code = models.PositiveIntegerField()
    contact_name = models.CharField(max_length=100)
    contact_phone = PhoneField()
    account = models.ForeignKey(AccountCompany, on_delete=models.CASCADE)

    def __str__(self):
        return self.address1 +' '+ self.address2 +' '+ self.city

    def get_absolute_url(self):
        return reverse("customer_app:jobsites")
    

customer/forms.py
from django import forms
from .models import *

class CustomerCreateForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('fname','lname','email','phone_number','company','note',)
        

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["fname"].label = "First Name"
        self.fields["lname"].label = "Last Name"

class CompanyCreateForm(forms.ModelForm):
    class Meta:
        model = Company
        exclude = ('account',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["address1"].label = "Address"
        self.fields["address2"].label = "Address 2"
    
class JobsiteCreateForm(forms.ModelForm):
    class Meta:
        model = Jobsite
        exclude = ('account',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["address1"].label = "Address"
        self.fields["address2"].label = "Address 2"

customer/views.py
from django.shortcuts import render
from django.http import request
from .forms import CompanyCreateForm, CustomerCreateForm, JobsiteCreateForm
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from .models import Customer,Company,Jobsite
from customer.forms import CustomerCreateForm
from service_ticket_app.utils import *
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


class CompanyCreateView(LoginRequiredMixin,CreateView):
    model = Company
    form_class = CompanyCreateForm

    def form_valid(self, form):
        form.instance.account = self.request.user.accountuser.account
        return super(CompanyCreateView, self).form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ticket_count'] = ticket_count(self.request)
        context['tech_ticket_count'] = tech_ticket_count(self.request)
        context['todays_tickets'] = todays_tickets(self.request)
        context['tech_todays_tickets'] = tech_todays_tickets(self.request)
        context['todays_tickets_count'] = todays_tickets_count(self.request)
        context['in_progress_count'] = in_progress_count(self.request)
        context['completed_today_tickets_count'] = completed_today_tickets_count(self.request)
        context['tech_todays_tickets_count'] = tech_todays_tickets_count(self.request)
        context['tech_completed_today_tickets_count'] = tech_completed_today_tickets_count(self.request)
        return context

class CompanyListView(LoginRequiredMixin,ListView):
    model = Company
    context_object_name = 'company'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ticket_count'] = ticket_count(self.request)
        context['tech_ticket_count'] = tech_ticket_count(self.request)
        context['todays_tickets'] = todays_tickets(self.request)
        context['tech_todays_tickets'] = tech_todays_tickets(self.request)
        context['todays_tickets_count'] = todays_tickets_count(self.request)
        context['in_progress_count'] = in_progress_count(self.request)
        context['completed_today_tickets_count'] = completed_today_tickets_count(self.request)
        context['tech_todays_tickets_count'] = tech_todays_tickets_count(self.request)
        context['tech_completed_today_tickets_count'] = tech_completed_today_tickets_count(self.request)
        context['company'] = company(self.request)
        return context

class CompanyUpdateView(LoginRequiredMixin,UpdateView):
    model = Company
    form_class = CompanyCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ticket_count'] = ticket_count(self.request)
        context['tech_ticket_count'] = tech_ticket_count(self.request)
        context['todays_tickets'] = todays_tickets(self.request)
        context['tech_todays_tickets'] = tech_todays_tickets(self.request)
        context['todays_tickets_count'] = todays_tickets_count(self.request)
        context['in_progress_count'] = in_progress_count(self.request)
        context['completed_today_tickets_count'] = completed_today_tickets_count(self.request)
        context['tech_todays_tickets_count'] = tech_todays_tickets_count(self.request)
        context['tech_completed_today_tickets_count'] = tech_completed_today_tickets_count(self.request)
        return context

class CompanyDeleteView(LoginRequiredMixin, DeleteView):
    model = Company
    success_url = reverse_lazy('customer_app:companies') 

class CustomerCreateView(LoginRequiredMixin,CreateView):
    model = Customer
    form_class = CustomerCreateForm

    def get_form(self, form_class=None):
        form = super(CustomerCreateView, self).get_form(form_class)
        form.fields['company'].queryset = Company.objects.filter(account=self.request.user.accountuser.account)
        return form

    def form_valid(self, form):
        form.instance.account = self.request.user.accountuser.account
        return super(CustomerCreateView, self).form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ticket_count'] = ticket_count(self.request)
        context['tech_ticket_count'] = tech_ticket_count(self.request)
        context['todays_tickets'] = todays_tickets(self.request)
        context['tech_todays_tickets'] = tech_todays_tickets(self.request)
        context['todays_tickets_count'] = todays_tickets_count(self.request)
        context['in_progress_count'] = in_progress_count(self.request)
        context['completed_today_tickets_count'] = completed_today_tickets_count(self.request)
        context['tech_todays_tickets_count'] = tech_todays_tickets_count(self.request)
        context['tech_completed_today_tickets_count'] = tech_completed_today_tickets_count(self.request)
        return context

class CustomerListView(LoginRequiredMixin,ListView):
    model = Customer
    context_object_name = 'customer'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ticket_count'] = ticket_count(self.request)
        context['tech_ticket_count'] = tech_ticket_count(self.request)
        context['todays_tickets'] = todays_tickets(self.request)
        context['tech_todays_tickets'] = tech_todays_tickets(self.request)
        context['todays_tickets_count'] = todays_tickets_count(self.request)
        context['in_progress_count'] = in_progress_count(self.request)
        context['completed_today_tickets_count'] = completed_today_tickets_count(self.request)
        context['tech_todays_tickets_count'] = tech_todays_tickets_count(self.request)
        context['tech_completed_today_tickets_count'] = tech_completed_today_tickets_count(self.request)
        context['customer'] = customer(self.request)
        return context

class CustomerUpdateView(LoginRequiredMixin,UpdateView):
    model = Customer
    form_class = CustomerCreateForm
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ticket_count'] = ticket_count(self.request)
        context['tech_ticket_count'] = tech_ticket_count(self.request)
        context['todays_tickets'] = todays_tickets(self.request)
        context['tech_todays_tickets'] = tech_todays_tickets(self.request)
        context['todays_tickets_count'] = todays_tickets_count(self.request)
        context['in_progress_count'] = in_progress_count(self.request)
        context['completed_today_tickets_count'] = completed_today_tickets_count(self.request)
        context['tech_todays_tickets_count'] = tech_todays_tickets_count(self.request)
        context['tech_completed_today_tickets_count'] = tech_completed_today_tickets_count(self.request)
        return context

class CustomerDeleteView(LoginRequiredMixin, DeleteView):
    model = Customer
    success_url = reverse_lazy('customer_app:customers') 
    
class JobsiteCreateView(LoginRequiredMixin,CreateView):
    model = Jobsite
    form_class = JobsiteCreateForm

    def form_valid(self, form):
        form.instance.account = self.request.user.accountuser.account
        return super(JobsiteCreateView, self).form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ticket_count'] = ticket_count(self.request)
        context['tech_ticket_count'] = tech_ticket_count(self.request)
        context['todays_tickets'] = todays_tickets(self.request)
        context['tech_todays_tickets'] = tech_todays_tickets(self.request)
        context['todays_tickets_count'] = todays_tickets_count(self.request)
        context['in_progress_count'] = in_progress_count(self.request)
        context['completed_today_tickets_count'] = completed_today_tickets_count(self.request)
        context['tech_todays_tickets_count'] = tech_todays_tickets_count(self.request)
        context['tech_completed_today_tickets_count'] = tech_completed_today_tickets_count(self.request)
        return context

class JobsiteListView(LoginRequiredMixin,ListView):
    model = Jobsite
    context_object_name = 'jobsite'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ticket_count'] = ticket_count(self.request)
        context['tech_ticket_count'] = tech_ticket_count(self.request)
        context['todays_tickets'] = todays_tickets(self.request)
        context['tech_todays_tickets'] = tech_todays_tickets(self.request)
        context['todays_tickets_count'] = todays_tickets_count(self.request)
        context['in_progress_count'] = in_progress_count(self.request)
        context['completed_today_tickets_count'] = completed_today_tickets_count(self.request)
        context['tech_todays_tickets_count'] = tech_todays_tickets_count(self.request)
        context['tech_completed_today_tickets_count'] = tech_completed_today_tickets_count(self.request)
        context['jobsite'] = jobsite(self.request)
        return context

class JobsiteUpdateView(LoginRequiredMixin,UpdateView):
    model = Jobsite
    form_class = JobsiteCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ticket_count'] = ticket_count(self.request)
        context['tech_ticket_count'] = tech_ticket_count(self.request)
        context['todays_tickets'] = todays_tickets(self.request)
        context['tech_todays_tickets'] = tech_todays_tickets(self.request)
        context['todays_tickets_count'] = todays_tickets_count(self.request)
        context['in_progress_count'] = in_progress_count(self.request)

customer/templates/customer/company_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<h1> Are you sure you want to delete {{ company.name }}?</h1>

<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger btn-rounded" value="Delete">
    <a href="{% url 'customer_app:companies' %}" type='button' class='btn btn-outline-dark btn-rounded'>Cancel</a>
</form>

{% endblock %}

customer/templates/customer/company_form.html
{% extends 'base.html'%}
{% load bootstrap4 %}
{% block content %}
    <h2>
{% if not form.instance.pk %}
        Add New Company
    {% elif user.accountuser.role == 'Admin' %}
        Admin Edit
    {% else %}
        Edit
{% endif %}
    </h2>
    <form method='POST'>
        {% csrf_token %}
        {% bootstrap_form form %}
        <input class='btn btn-outline-primary' type="submit" value='Save'>
    </form>
{% endblock %}

customer/templates/customer/company_list.html
{% extends 'base.html' %}
{% block content %}


<!-- Table with panel -->
<div class="card card-cascade narrower">
    <!--Card image-->
    <div class="view view-cascade gradient-card-header blue-gradient narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">
        <div>
            <div class="white-text mx-3">{{request.user.accountuser.account}} Companies</div>
        </div>
        <div class='justify-content-start'>
            <a href="{% url 'customer_app:add_company' %}" type="button" class="btn btn-outline-white btn-sm px-2">
                <i class="fas fa-plus mt-0"></i> New Company
            </a> 
        </div>
    </div>
    <!--/Card image-->
    <div class="px-5">
        <div class="table-wrapper">
            {% comment %} <h2 class='mb-3'>Basic example</h2> {% endcomment %}
            <table id="ticket_list" class="table table-hover table-sm table-responsive-sm" width="100%">
                <thead>
                    <tr>
                        <th class="th-sm">Name
                        </th>
                        <th class="th-sm">Address
                        </th>
                        <th class="th-sm">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for c in company %}
                        <tr>
                            <td>{{ c.name }}</td>
                            <td> {{ c.address1 }} {{ c.address2 }}, {{ c.city }} {{ c.state }} {{ c.zip_code }}  </td>
                            <td>
                                <a href="{% url 'customer_app:edit_company' pk=c.pk %}" type="button" class="btn btn-outline-blue btn-rounded btn-sm px-2">
                                    <i class="fas fa-pencil-alt lt mt-0"></i>
                                </a>
                                <a href="{% url 'customer_app:delete_company' pk=c.pk %}" type="button" class="btn btn-outline-danger btn-rounded btn-sm px-2">
                                    <i class="fas fa-trash-alt lt mt-0"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- Table with panel -->


{% endblock %}

customer/templates/customer/customer_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<h1> Are you sure you want to delete {{ customer.fname }} {{customer.lname}}?</h1>

<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger btn-rounded" value="Delete">
    <a href="{% url 'customer_app:customers' %}" type='button' class='btn btn-outline-dark btn-rounded'>Cancel</a>
</form>

{% endblock %}

customer/templates/customer/customer_form.html
{% extends 'base.html'%}
{% load bootstrap4 %}
{% block content %}
    <h2>
{% if not form.instance.pk %}
        Add New Customer
    {% elif user.accountuser.role == 'Admin' %}
        Admin Edit
    {% else %}
        Edit
{% endif %}
    </h2>
    <form method='POST'>
        {% csrf_token %}
        {% bootstrap_form form %}
        <input class='btn btn-outline-primary' type="submit" value='Save'>
    </form>
{% endblock %}

customer/templates/customer/customer_list.html
{% extends 'base.html' %}
{% block content %}


<!-- Table with panel -->
<div class="card card-cascade narrower">
    <!--Card image-->
    <div class="view view-cascade gradient-card-header blue-gradient narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">
        <div>
            <div class="white-text mx-3">{{request.user.accountuser.account}} Customers</div>
        </div>
        <div class='justify-content-start'>
            <a href="{% url 'customer_app:add_customer' %}" type="button" class="btn btn-outline-white btn-sm px-2">
                <i class="fas fa-plus mt-0"></i> New Customer
            </a> 
        </div>
    </div>
    <!--/Card image-->
    <div class="px-5">
        <div class="table-wrapper">
            {% comment %} <h2 class='mb-3'>Basic example</h2> {% endcomment %}
            <table id="ticket_list" class="table table-hover table-sm table-responsive-sm" width="100%">
                <thead>
                    <tr>
                        <th class="th-sm">Name
                        </th>
                        <th class="th-sm">Email
                        </th>
                        <th class="th-sm">Phone
                        </th>
                        <th class="th-sm">Company
                        </th>
                        <th class="th-sm">Note
                        </th>
                        <th class="th-sm">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for c in customer %}
                        <tr>
                            <td>{{ c.fname }} {{ c.lname }}</td>
                            <td> {{ c.email }} </td>
                            <td> {{ c.phone_number }}</td>
                            <td> {{ c.company }}</td>
                            <td> {{ c.note }}</td>
                            <td>
                                <a href="{% url 'customer_app:edit_customer' pk=c.pk %}" type="button" class="btn btn-outline-blue btn-rounded btn-sm px-2">
                                    <i class="fas fa-pencil-alt lt mt-0"></i>
                                </a>
                                <a href="{% url 'customer_app:delete_customer' pk=c.pk %}" type="button" class="btn btn-outline-danger btn-rounded btn-sm px-2">
                                    <i class="fas fa-trash-alt lt mt-0"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- Table with panel -->


{% endblock %}

customer/templates/customer/jobsite_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<h1> Are you sure you want to delete {{ jobsite.address1 }} {{ jobsite.address2 }}, {{ jobsite.city }}?</h1>

<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger btn-rounded" value="Delete">
    <a href="{% url 'customer_app:jobsites' %}" type='button' class='btn btn-outline-dark btn-rounded'>Cancel</a>
</form>

{% endblock %}

customer/templates/customer/jobsite_form.html
{% extends 'base.html'%}
{% load bootstrap4 %}
{% block content %}
    <h2>
{% if not form.instance.pk %}
        Add New Jobsite
    {% elif user.accountuser.role == 'Admin' %}
        Admin Edit
    {% else %}
        Edit
{% endif %}
    </h2>
    <form method='POST'>
        {% csrf_token %}
        {% bootstrap_form form %}
        <input class='btn btn-rounded btn-primary' type="submit" value='Save'>
    </form>
{% endblock %}

customer/templates/customer/jobsite_list.html
{% extends 'base.html' %}
{% block content %}


<!-- Table with panel -->
<div class="card card-cascade narrower">
    <!--Card image-->
    <div class="view view-cascade gradient-card-header blue-gradient narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">
        <div>
            <div class="white-text mx-3">{{request.user.accountuser.account}} Jobsites</div>
        </div>
        <div class='justify-content-start'>
            <a href="{% url 'customer_app:add_jobsite' %}" type="button" class="btn btn-outline-white  btn-sm px-2">
                <i class="fas fa-plus mt-0"></i> New Jobsite
            </a> 
        </div>
    </div>
    <!--/Card image-->
    <div class="px-5">
        <div class="table-wrapper">
            {% comment %} <h2 class='mb-3'>Basic example</h2> {% endcomment %}
            <table id="ticket_list" class="table table-hover table-sm table-responsive-sm" width="100%">
                <thead>
                    <tr>
                        <th class="th-sm">Contact
                        </th>
                        <th class="th-sm">Phone
                        </th>
                        <th class="th-sm">Address
                        </th>
                        <th class="th-sm">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for c in jobsite %}
                        <tr>
                            <td>{{ c.contact_name }}</td>
                            <td>{{ c.contact_phone }}</td>
                            <td> {{ c.address1 }} {{ c.address2 }}, {{ c.city }} {{ c.state }} {{ c.zip_code }}  </td>
                            <td>
                                <a href="{% url 'customer_app:edit_jobsite' pk=c.pk %}" type="button" class="btn btn-outline-blue btn-rounded btn-sm px-2">
                                    <i class="fas fa-pencil-alt lt mt-0"></i>
                                </a>
                                <a href="{% url 'customer_app:delete_jobsite' pk=c.pk %}" type="button" class="btn btn-outline-danger btn-rounded btn-sm px-2">
                                    <i class="fas fa-trash-alt lt mt-0"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- Table with panel -->


{% endblock %}