customer/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from customer import views

app_name = 'customer_app'

urlpatterns = [
    
    # Customers
    path('customers/', views.CustomerListView.as_view(),name='customers'),
    path('add-customer/',views.CustomerCreateView.as_view(), name="add_customer"),
    path('delete-customer-<pk>/',views.CustomerDeleteView.as_view(), name='delete_customer'),
    path('edit-<pk>/', views.CustomerUpdateView.as_view(), name='edit_customer'),
    # Companies
    path('companies/', views.CompanyListView.as_view(),name='companies'),
    path('add-company/',views.CompanyCreateView.as_view(), name="add_company"),
    path('delete-company-<pk>/',views.CompanyDeleteView.as_view(), name='delete_company'),
    path('company-edit-<pk>/', views.CompanyUpdateView.as_view(), name='edit_company'),
    # Jobsites
    path('jobsites/', views.JobsiteListView.as_view(),name='jobsites'),
    path('add-jobsite/',views.JobsiteCreateView.as_view(), name="add_jobsite"),
    path('delete-jobsite-<pk>/',views.JobsiteDeleteView.as_view(), name='delete_jobsite'),
    path('jobsite-edit-<pk>/', views.JobsiteUpdateView.as_view(), name='edit_jobsite'),
]

part/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from part import views

app_name = 'customer'

urlpatterns = [
    
]

service_ticket_app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('customer.urls')),
    path('', include('ticket.urls')),
    path('',include('upcoming.urls')),
    path('',include('part.urls')),
    path('', views.TodayView.as_view(), name='today'),
    path('accounts/login/', views.user_login, name='login'),
    path('schedule/',views.CalendarView.as_view(), name='schedule'),
    path('logged_out/',views.user_logout, name='user_logout'),
]

ticket/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

app_name = 'ticket_app'
urlpatterns = [
    path('new-ticket/', views.TicketCreateView.as_view(), name='new_ticket'),
    path('tickets/', views.TicketListView.as_view(), name='all_tickets'),
    path('ticket/<pk>/', views.TicketDetailView.as_view(), name='ticket_detail'),
    path('update/<pk>/', views.TicketUpdateView.as_view(), name='ticket_update'),
    path('update-<pk>/', views.TechTicketUpdateView.as_view(), name='tech_ticket_update'),
    path('update/c/<pk>/', views.TechTicketCompleteUpdateView.as_view(), name='tech_ticket_complete_update'),
    path('delete/<pk>', views.TicketDeleteView.as_view(), name='ticket_delete'),
    path('new_type/', views.TicketTypeCreateView.as_view(), name='new_ticket_type'),
    path('ticket-types/', views.TicketTypeListView.as_view(), name='ticket_type_list'),
    path('delete-type/<pk>', views.TicketTypeDeleteView.as_view(), name='tickettype_delete'),
    path('new-service/', views.ServiceProvidedCreateView.as_view(), name='new_serviceprovided'),
    path('services/', views.ServiceProvidedListView.as_view(), name='serviceprovided_list'),
    path('delete-service-<pk>/', views.ServiceProvidedDeleteView.as_view(), name='delete_serviceprovided'),
    path('reports/', views.reports, name='reports')
]

ticket/forms.py
from django import forms
from django.contrib.auth.models import User
from django.db.models.query import QuerySet

from django.forms.models import inlineformset_factory

from .models import *



class TicketForm(forms.ModelForm):
    """
    Form used for creating a Ticket
    """
    class Meta:
        model = Ticket
        fields = 'ticket_number','t_customer','t_jobsite','assigned','stop','department','t_type','scope','repair_notes','additional_work','schedule','start_job','completed',

     

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["t_customer"].label = "Sold To"
        self.fields["t_jobsite"].label = "Jobsite"
        self.fields["assigned"].label = "Technician"
        self.fields["department"].label = "Dept"
        self.fields["t_type"].label = "Service Type"

class TicketUpdateForm(forms.ModelForm):
    """
    Used for updating the Ticket model when logged in as an Admin
    """
    ticket_number = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    
    class Meta:
        model = Ticket
        fields = ('ticket_number','t_customer','t_jobsite','assigned','stop','department','t_type','scope','repair_notes','additional_work','schedule','start_time','end_time','start_job','completed',)
        

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["t_customer"].label = "Sold To"
        self.fields["t_jobsite"].label = "Jobsite"
        self.fields["assigned"].label = "Technician"
        self.fields["department"].label = "Dept"
        self.fields["t_type"].label = "Service Type"
        
        
class TechTicketUpdateForm(forms.ModelForm):
    """
    Form used for technicians to update parts of the Ticket model
    """
    ticket_number = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    
    class Meta:
        model = Ticket
        fields = ('ticket_number','start_job',)

class TechTicketCompleteUpdateForm(forms.ModelForm):
    """
    Form used for technicians to update parts of the Ticket model
    """
    ticket_number = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    
    class Meta:
        model = Ticket
        fields = ('ticket_number','completed','repair_notes','additional_work')      

ticket/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)
from service_ticket_app.utils import *

from ticket.forms import TechTicketCompleteUpdateForm, TechTicketUpdateForm, TicketForm, TicketUpdateForm

from .filters import TicketFilter
from .models import Ticket

# Create your views here.

class TicketCreateView(LoginRequiredMixin,CreateView):
    model = Ticket
    form_class = TicketForm
    
    def get_form(self, form_class=None):
        """
        Gets the form and filters the fields to only show information related the the logged in users account
        """
        form = super(TicketCreateView, self).get_form(form_class)
        form.fields['assigned'].queryset = AccountUser.objects.filter(account=self.request.user.accountuser.account)
        form.fields['t_customer'].queryset = Customer.objects.filter(account=self.request.user.accountuser.account)
        form.fields['t_jobsite'].queryset = Jobsite.objects.filter(account=self.request.user.accountuser.account)
        form.fields['department'].queryset = ServiceProvided.objects.filter(account=self.request.user.accountuser.account)
        form.fields['t_type'].queryset = TicketType.objects.filter(account=self.request.user.accountuser.account)
        return form

    def form_valid(self, form):
        """
        Uopn a valid form, assigns the logged in users account to the account of the Ticket model
        """
        form.instance.account = self.request.user.accountuser.account
        return super(TicketCreateView, self).form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ticket_count'] = ticket_count(self.request)
        context['tech_ticket_count'] = tech_ticket_count(self.request)
        context['todays_tickets'] = todays_tickets(self.request)
        context['tech_todays_tickets'] = tech_todays_tickets(self.request)
        context['todays_tickets_count'] = todays_tickets_count(self.request)
        context['in_progress_count'] = in_progress_count(self.request)
        context['completed_today_tickets_count'] = completed_today_tickets_count(self.request)
        context['tech_todays_tickets_count'] = tech_todays_tickets_count(self.request)
        context['tech_completed_today_tickets_count'] = tech_completed_today_tickets_count(self.request)
        context['company_count'] = company_count(self.request)
        context['customer_count'] = customer_count(self.request)
        context['jobsite_count'] = jobsite_count(self.request)
        return context

class TicketListView(LoginRequiredMixin,ListView):
    model = Ticket
    context_object_name = 'ticket'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tech_ticket'] = tech_tickets(self.request)
        context['ticket_count'] = ticket_count(self.request)
        context['tech_ticket_count'] = tech_ticket_count(self.request)
        context['todays_tickets'] = todays_tickets(self.request)
        context['tech_todays_tickets'] = tech_todays_tickets(self.request)
        context['todays_tickets_count'] = todays_tickets_count(self.request)
        context['in_progress_count'] = in_progress_count(self.request)
        context['completed_today_tickets_count'] = completed_today_tickets_count(self.request)
        context['tech_todays_tickets_count'] = tech_todays_tickets_count(self.request)
        context['tech_completed_today_tickets_count'] = tech_completed_today_tickets_count(self.request)
        context['ticket'] = ticket(self.request)
        return context 
    
class TicketDetailView(LoginRequiredMixin, DetailView):
    context_object_name = 'ticket'
    model = Ticket
    template_name = 'ticket/ticket_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ticket_count'] = ticket_count(self.request)
        context['tech_ticket_count'] = tech_ticket_count(self.request)
        context['todays_tickets'] = todays_tickets(self.request)
        context['tech_todays_tickets'] = tech_todays_tickets(self.request)
        context['todays_tickets_count'] = todays_tickets_count(self.request)
        context['in_progress_count'] = in_progress_count(self.request)
        context['completed_today_tickets_count'] = completed_today_tickets_count(self.request)
        context['tech_todays_tickets_count'] = tech_todays_tickets_count(self.request)
        context['tech_completed_today_tickets_count'] = tech_completed_today_tickets_count(self.request)
        context['history'] = Ticket.objects.filter(t_jobsite=self.get_object().t_jobsite, account=self.request.user.accountuser.account, completed=True).order_by('end_time')
        return context  

class TicketUpdateView(LoginRequiredMixin,UpdateView):
    model = Ticket
    form_class = TicketUpdateForm

    def get_form(self, form_class=None):
        """
        Gets the form and filters the fields to only show information related the the logged in users account
        """
        form = super(TicketUpdateView, self).get_form(form_class)
        form.fields['assigned'].queryset = AccountUser.objects.filter(account=self.request.user.accountuser.account)
        form.fields['t_customer'].queryset = Customer.objects.filter(account=self.request.user.accountuser.account)
        form.fields['t_jobsite'].queryset = Jobsite.objects.filter(account=self.request.user.accountuser.account)
        form.fields['department'].queryset = ServiceProvided.objects.filter(account=self.request.user.accountuser.account)
        form.fields['t_type'].queryset = TicketType.objects.filter(account=self.request.user.accountuser.account)
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ticket_count'] = ticket_count(self.request)
        context['tech_ticket_count'] = tech_ticket_count(self.request)
        context['todays_tickets'] = todays_tickets(self.request)
        context['tech_todays_tickets'] = tech_todays_tickets(self.request)
        context['todays_tickets_count'] = todays_tickets_count(self.request)
        context['in_progress_count'] = in_progress_count(self.request)
        context['completed_today_tickets_count'] = completed_today_tickets_count(self.request)
        context['tech_todays_tickets_count'] = tech_todays_tickets_count(self.request)
        context['tech_completed_today_tickets_count'] = tech_completed_today_tickets_count(self.request)
        # context['formset'] = PartsTicketFormSet(instance=Part())
        return context 

class TechTicketUpdateView(LoginRequiredMixin, UpdateView):
    model = Ticket
    form_class = TechTicketUpdateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ticket_count'] = ticket_count(self.request)
        context['tech_ticket_count'] = tech_ticket_count(self.request)
        context['todays_tickets'] = todays_tickets(self.request)
        context['tech_todays_tickets'] = tech_todays_tickets(self.request)
        context['todays_tickets_count'] = todays_tickets_count(self.request)
        context['in_progress_count'] = in_progress_count(self.request)
        context['completed_today_tickets_count'] = completed_today_tickets_count(self.request)
        context['tech_todays_tickets_count'] = tech_todays_tickets_count(self.request)
        context['tech_completed_today_tickets_count'] = tech_completed_today_tickets_count(self.request)

        return context

class TechTicketCompleteUpdateView(LoginRequiredMixin, UpdateView):
    model = Ticket
    form_class = TechTicketCompleteUpdateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ticket_count'] = ticket_count(self.request)
        context['tech_ticket_count'] = tech_ticket_count(self.request)
        context['todays_tickets'] = todays_tickets(self.request)
        context['tech_todays_tickets'] = tech_todays_tickets(self.request)
        context['todays_tickets_count'] = todays_tickets_count(self.request)
        context['in_progress_count'] = in_progress_count(self.request)
        context['completed_today_tickets_count'] = completed_today_tickets_count(self.request)
        context['tech_todays_tickets_count'] = tech_todays_tickets_count(self.request)
        context['tech_completed_today_tickets_count'] = tech_completed_today_tickets_count(self.request)

        return context

class TicketDeleteView(LoginRequiredMixin, DeleteView):
    model = Ticket
    success_url = reverse_lazy('ticket_app:all_tickets') 

class TicketTypeCreateView(LoginRequiredMixin, CreateView):
    model = TicketType
    fields = ('name',)

    def form_valid(self, form):
        form.instance.account = self.request.user.accountuser.account
        return super(TicketTypeCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tech_ticket'] = tech_tickets(self.request)
        context['ticket_count'] = ticket_count(self.request)
        context['tech_ticket_count'] = tech_ticket_count(self.request)
        context['todays_tickets'] = todays_tickets(self.request)
        context['tech_todays_tickets'] = tech_todays_tickets(self.request)
        context['todays_tickets_count'] = todays_tickets_count(self.request)
        context['in_progress_count'] = in_progress_count(self.request)
        context['completed_today_tickets_count'] = completed_today_tickets_count(self.request)
        context['tech_todays_tickets_count'] = tech_todays_tickets_count(self.request)

ticket/templates/ticket/serviceprovided_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<h1> Are you sure you want to delete {{ serviceprovided.name }}?</h1>

<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger btn-rounded" value="Delete">
    <a href="{% url 'ticket_app:serviceprovided_list' %}" type='button' class='btn btn-outline-dark btn-rounded'>Cancel</a>
</form>

{% endblock %}

ticket/templates/ticket/serviceprovided_list.html
{% extends 'base.html' %}
{% block content %}
<div class="row justify-content-between mb-5">
  <div class='col-3'>
    <h2>Services</h2>
    <hr>
  </div>
  <div class='col-1'> 
    <a href="{% url 'ticket_app:new_serviceprovided' %}" type='button' class='btn btn-sm btn-rounded btn-outline-primary'><i class="fas fa-plus text-primary"></i></a>
    </a>
  </div>
</div>


<ul class="list-group">
{% for s in serviceprovided %}
  <li class="list-group-item">
    <div class="row justify-content-between">
      <div class='col-4'>
        {{s.name}}
      </div>
      <div class='col-1'> 
        <a href="{% url 'ticket_app:delete_serviceprovided' pk=s.id %}" type="button" class="btn btn-outline-danger btn-rounded btn-sm px-2">
          <i class="far fa-trash-alt mt-0"></i>
        </a>
      </div>
    </div>
  </li>
{% endfor %}
</ul>
{% endblock %}

ticket/templates/ticket/ticket_detail.html
{% extends 'base.html' %}
{% load tz %}
{% block content %}
<div>
    {% if user.accountuser.role == 'Admin' %}
        <a href="{% url 'ticket_app:all_tickets' %}" type="button" class="btn btn-outline-blue btn-rounded btn-sm px-2">
            <i class="fas fa-arrow-left lt mt-0"></i>
        </a>
        <a href="{% url 'ticket_app:ticket_update' pk=ticket.ticket_number %}" type="button" class="btn btn-outline-blue btn-rounded btn-sm px-2">
            <i class="fas fa-pencil-alt lt mt-0"></i>
        </a>
        {% if ticket.ticket_number == '10001' %}
            
        {% else %}
            <a href="{% url 'ticket_app:ticket_delete' pk=ticket.ticket_number %}" type="button" class="btn btn-outline-danger btn-rounded btn-sm px-2">
                <i class="far fa-trash-alt mt-0"></i>
            </a>
        {% endif %}
    {% else %}
        <a href="{% url 'ticket_app:all_tickets' %}" type="button" class="btn btn-outline-blue btn-rounded btn-sm px-2">
            <i class="fas fa-arrow-left lt mt-0"></i>
        </a>
    {% endif %}
    <div class="row justify-content-between">
        <div class="col-3">
            <small>
            {% localtime on %}
                Created: {{ ticket.created_at|localtime }}
            </small>
            {% endlocaltime %}
        </div>
        <div class="col-3 ml-auto">
            <small>

                Updated: {{ ticket.updated_at }}
            </small>
        </div>
    </div>
    <div class="jumbotron p-2 mb-2">
        <div class="row text-center">
        {% if not ticket.start_time %}
            <div class="col-12">
                Click <a href="{% url 'ticket_app:tech_ticket_update' pk=ticket.ticket_number %}" type="button" class="btn btn-outline-blue btn-rounded btn-sm px-2">
                    <i class="fas fa-play-circle lt mt-0"></i>
                </a> to start job.
            </div>
        {% else %}
            <div class="col-4">
            {% localtime on %}
                Start: {{ ticket.start_time|time }}
            {% endlocaltime %}
            </div>
            <div class="col-4">
            {% if not ticket.end_time %}
                Click <a href="{% url 'ticket_app:tech_ticket_complete_update' pk=ticket.ticket_number %}" type="button" class="btn btn-outline-blue btn-rounded btn-sm px-2">
                    <i class="fas fa-flag-checkered lt mt-0"></i>
                </a> to complete job.
            {% else %}
            {% localtime on %}
                End:  {{ ticket.end_time|time }}
            {% endlocaltime %}
            {% endif %}
            </div>
            <div class="col-4">
                Total: {{ ticket.start_time|timesince:ticket.end_time}}
            
            </div>
        {% endif %}
        </div>
    </div>
</div>
<div class="row mb-2">
    <div class="col-md-6">
        <div class="card h-100">
            <div class="card-body">
                <h5 class="card-title text-center">
                    Jobsite
                </h5>
                <label for="card-text">Address</label>
                <p class="card-text">
                    {{ ticket.t_jobsite.address1 }} {{ ticket.t_jobsite.addres2 }}
                </p>
                <p class="card-text">
                    {{ ticket.t_jobsite.city }}, {{ ticket.t_jobsite.state }}, {{ ticket.t_jobsite.zip_code }}
                </p>
                <label for="card-text">Contact</label>
                <p class="card-text">
                    {{ ticket.t_jobsite.contact_name }} - {{ ticket.t_jobsite.contact_phone }}
                </p>                
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card h-100">
            <div class="card-body">
                <h5 class="card-title text-center">
                    Sold To
                </h5>
                <div class="row">
                    <div class="col-md">
                        <label for="card-text">Name</label>
                        <p class="card-text">
                            {{ ticket.t_customer.fname }} {{ ticket.t_customer.lname }} - {{ ticket.t_customer.company.name}}
                        </p>
                    </div>
                    <div class="col-md">
                        <label for="card-text"> Email/Phone</label>
                        <p class="card-text">
                            {{ ticket.t_customer.email }} - {{ ticket.t_customer.phone_number }}
                        </p>
                    </div>
                </div>
                <div class='row'>
                    <div class="col-md">
                        <label for="card-text">Address</label>
                        <p class="card-text">{{ ticket.t_customer.company.address1 }} {{ ticket.t_customer.company.address2 }}</p>
                        <p class="card-text">{{ ticket.t_customer.company.city }}, {{ ticket.t_customer.company.state }} {{ticket.t_customer.company.zip_code }}</p>
                    </div>
                </div>
                <label for="card-text">Notes</label>
                <p class="card-text">
                    {{ ticket.t_customer.note }}
                </p>                
            </div>
        </div>
    </div>
</div>
<div class="jumbotron p-1 mb-2">
    <div class="row text-center">
        <div class="col-4">
        Ticket # {{ ticket.ticket_number }}
        </div>
        <div class="col-4">
            {{ ticket.department }}
        </div>
        <div class="col-4">
            {{ ticket.t_type }} Call
        </div>
    </div>
</div>
<div class="jumbotron pt-2 mb-2">
    <div class="row">
        <label class="lead">
            Scope
        </label>
    </div>
    <div class="row">
        <p>
            {{ ticket.scope }}
        </p>         
    </div>
</div>
{% if not ticket.repair_notes %}
{% else %}
<div class="jumbotron pt-2 mb-2">
    <div class="row">
        <label class="lead">
            Work Done
        </label>
    </div>
    <div class="row">
        <p>
            {{ ticket.repair_notes }}
        </p>         
    </div>
</div>
{% endif %}
{% if not ticket.additional_work %}
{% else %}
<div class="jumbotron pt-2">
    <div class="row">
        <label class="lead">
            Additional Work
        </label>
    </div>
    <div class="row">
        <p>
            {{ ticket.additional_work }}
        </p>         
    </div>
</div>
{% endif %}
{% if not history %}
{% else %}
<div class="jumbotron pt-2">
    <div class="row">
        <label class="lead">
           Jobsite History
        </label>
    </div>
    <div class="row">
    {% for h in history %}
        {% if h.ticket_number == ticket.ticket_number %}
        {% else %}
            <div class='col-12'>
                <a href="{% url 'ticket_app:ticket_detail' pk=h.ticket_number %}" type="button" class="btn btn-outline-blue btn-block btn-rounded m-2 px-5">
                <div class="row">
                    <div class="col-lg">
                        <b>Ticket  #</b> {{ h.ticket_number }}
                    </div>
                    <div class="col-lg">
                    <b>Scope of work:</b> {{ h.scope|truncatechars:50 }}
                    </div>
                    <div class="col-lg">
                        <b>Completed on:</b> {{ h.end_time|date }}
                    </div>
                    <div class="col-lg">
                        <b>by</b> 
                        {{ h.assigned }}
                    </div>
                </div>
                </a>
            </div> 
        {% endif %}
    {% endfor %}        
    </div>
</div>
{% endif %}

{% endblock %}

ticket/templates/ticket/ticket_form.html
{% extends 'base.html'%}
{% load bootstrap4 %}
{% block content %}

{% if company_count <= 0 %}
    <h5>
        Please add atleast one company to create a ticket!
        <a href="{% url 'customer_app:add_company' %}" type="button" class="btn btn-outline-primary btn-rounded btn-sm px-2"><i class="fas fa-user-plus mt-0"></i> 
        Company
        </a>    
    </h5>
{% elif customer_count <= 0 %}
    <h5>
        Please add atleast one customer to create a ticket!
        <a href="{% url 'customer_app:add_customer' %}" type="button" class="btn btn-outline-primary btn-rounded btn-sm px-2"><i class="fas fa-user-plus mt-0"></i> 
        Customer
        </a>    
    </h5>
{% elif jobsite_count <= 0 %}
    <h5>
        Please add atleast one jobsite to create a ticket!
        <a href="{% url 'customer_app:add_jobsite' %}" type="button" class="btn btn-outline-primary btn-rounded btn-sm px-2"><i class="fas fa-user-plus mt-0"></i> 
        Jobsite
        </a>    
    </h5>
{% else %}
    <h2>
    {% if not form.instance.pk %}
            Add New Service Ticket
        {% elif user.accountuser.role == 'Admin' %}
            Admin Edit
        {% else %}
            Edit
    {% endif %}
        </h2>
        <hr>
        <form method='POST' enctype = "multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
           
            
            <input class='btn btn-outline-primary' type="submit" value='Save'>
        </form>
{% endif %}
{% endblock %}

ticket/templates/ticket/ticket_list.html
{% extends 'base.html' %}
{% block content %}


<!-- Table with panel -->
<div class="card card-cascade narrower">
    <!--Card image-->
    <div class="view view-cascade gradient-card-header blue-gradient narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">
         <div>
            <div class="white-text mx-3">All Tickets</div>
        </div>
        <div class='justify-content-start'>
            <a href="{% url 'ticket_app:new_ticket' %}" type="button" class="btn btn-outline-white btn-sm px-2">
                <i class="fas fa-plus mt-0"></i> New Ticket
            </a>
        </div>
    </div>
    <!--/Card image-->
    <div class="px-5">
        <div class="table-wrapper">
            {% comment %} <h2 class='mb-3'>Basic example</h2> {% endcomment %}
            <table id="ticket_list" class="table table-hover table-sm table-responsive" width="100%">
                <thead>
                    <tr>
                        <th class="th-sm">Status
                        </th>
                        <th class="th-sm">Ticket
                        </th>
                        <th class="th-sm">Scheduled
                        </th>
                        <th class="th-sm">Customer
                        </th>
                        <th class="th-sm">Jobsite
                        </th>
                        <th class="th-sm">Scope
                        </th>
                        <th class="th-sm">Dept
                        </th>
                        <th class="th-sm">Call
                        </th>
                        <th class="th-sm">Tech
                        </th>
                        <th class="th-sm">Actions
                        </th>
                    </tr>
                </thead>
                <tbody>
                {% if user.accountuser.role == 'Admin' %}
                    {% for t in ticket %}
                    {% if t.completed == True %}
                        <tr class="green lighten-4">
                            <td>Completed</td>
                    {% elif t.start_job == True and t.completed == False %}
                        <tr class="blue lighten-4">
                            <td>In Progress</td>
                    {% else %}
                        <tr class="grey lighten-2">
                            <td>Incomplete</td>
                    {% endif %}
                            <td>{{ t.ticket_number }}</td>
                            <td> {{ t.schedule }} </td>
                            <td>{{ t.t_customer}}</td>
                            <td>{{ t.t_jobsite }}</td>
                            <td>{{ t.scope|truncatechars:20 }}</td>
                            <td>{{ t.department }}</td>
                            <td>{{ t.t_type }}</td>
                            <td>{{ t.assigned }}</td>
                            <td>
                                <a href="{% url 'ticket_app:ticket_detail' pk=t.ticket_number %}" type="button" class="btn btn-outline-blue btn-rounded btn-sm px-2">
                                    <i class="fas fa-eye lt mt-0"></i>
                                </a>
                                <a href="{% url 'ticket_app:ticket_update' pk=t.ticket_number %}" type="button" class="btn btn-outline-blue btn-rounded btn-sm px-2">
                                    <i class="fas fa-pencil-alt lt mt-0"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                    {% for t in tech_ticket %}
                    {% if t.completed == True %}
                        <tr class="green lighten-4">
                            <td>Completed</td>
                    {% elif t.start_job == True and t.completed == False %}
                        <tr class="blue lighten-4">
                            <td>In Progress</td>
                    {% else %}
                        <tr class="grey lighten-2">
                            <td>Incomplete</td>
                    {% endif %}
                            <td>{{ t.ticket_number }}</td>
                            <td> {{ t.schedule }} </td>
                            <td>{{ t.t_customer}}</td>
                            <td>{{ t.t_jobsite }}</td>
                            <td>{{ t.scope|truncatechars:20 }}</td>
                            <td>{{ t.department }}</td>
                            <td>{{ t.t_type }}</td>
                            <td>{{ t.assigned }}</td>
                            <td>
                                <a href="{% url 'ticket_app:ticket_detail' pk=t.ticket_number %}" type="button" class="btn btn-outline-blue btn-rounded btn-sm px-2">
                                    <i class="fas fa-eye lt mt-0"></i>
                                </a>
                                <a href="{% url 'ticket_app:tech_ticket_update' pk=t.ticket_number %}" type="button" class="btn btn-outline-blue btn-rounded btn-sm px-2">
                                    <i class="fas fa-pencil-alt lt mt-0"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                {% endif %}   
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- Table with panel -->


{% endblock %}