accounts/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from accounts import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('add-user/',views.add_user, name='add_user'),
    path('users/',views.UserListView.as_view(), name='users'),
    path('delete-user-<pk>/', views.UserDeleteView.as_view(), name='delete_user'),
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name='accounts/change_password.html',success_url = './'),name='change_password')
]

customer/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from customer import views

app_name = 'customer_app'

urlpatterns = [
    
    # Customers
    path('customers/', views.CustomerListView.as_view(),name='customers'),
    path('add-customer/',views.CustomerCreateView.as_view(), name="add_customer"),
    path('delete-customer-<pk>/',views.CustomerDeleteView.as_view(), name='delete_customer'),
    path('edit-<pk>/', views.CustomerUpdateView.as_view(), name='edit_customer'),
    # Companies
    path('companies/', views.CompanyListView.as_view(),name='companies'),
    path('add-company/',views.CompanyCreateView.as_view(), name="add_company"),
    path('delete-company-<pk>/',views.CompanyDeleteView.as_view(), name='delete_company'),
    path('company-edit-<pk>/', views.CompanyUpdateView.as_view(), name='edit_company'),
    # Jobsites
    path('jobsites/', views.JobsiteListView.as_view(),name='jobsites'),
    path('add-jobsite/',views.JobsiteCreateView.as_view(), name="add_jobsite"),
    path('delete-jobsite-<pk>/',views.JobsiteDeleteView.as_view(), name='delete_jobsite'),
    path('jobsite-edit-<pk>/', views.JobsiteUpdateView.as_view(), name='edit_jobsite'),
]

part/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from part import views

app_name = 'customer'

urlpatterns = [
    
]

service_ticket_app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('customer.urls')),
    path('', include('ticket.urls')),
    path('',include('upcoming.urls')),
    path('',include('part.urls')),
    path('', views.TodayView.as_view(), name='today'),
    path('accounts/login/', views.user_login, name='login'),
    path('schedule/',views.CalendarView.as_view(), name='schedule'),
    path('logged_out/',views.user_logout, name='user_logout'),
]

ticket/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

app_name = 'ticket_app'
urlpatterns = [
    path('new-ticket/', views.TicketCreateView.as_view(), name='new_ticket'),
    path('tickets/', views.TicketListView.as_view(), name='all_tickets'),
    path('ticket/<pk>/', views.TicketDetailView.as_view(), name='ticket_detail'),
    path('update/<pk>/', views.TicketUpdateView.as_view(), name='ticket_update'),
    path('update-<pk>/', views.TechTicketUpdateView.as_view(), name='tech_ticket_update'),
    path('update/c/<pk>/', views.TechTicketCompleteUpdateView.as_view(), name='tech_ticket_complete_update'),
    path('delete/<pk>', views.TicketDeleteView.as_view(), name='ticket_delete'),
    path('new_type/', views.TicketTypeCreateView.as_view(), name='new_ticket_type'),
    path('ticket-types/', views.TicketTypeListView.as_view(), name='ticket_type_list'),
    path('delete-type/<pk>', views.TicketTypeDeleteView.as_view(), name='tickettype_delete'),
    path('new-service/', views.ServiceProvidedCreateView.as_view(), name='new_serviceprovided'),
    path('services/', views.ServiceProvidedListView.as_view(), name='serviceprovided_list'),
    path('delete-service-<pk>/', views.ServiceProvidedDeleteView.as_view(), name='delete_serviceprovided'),
    path('reports/', views.reports, name='reports')
]

upcoming/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

app_name = 'upcoming'

urlpatterns = [
    path('upcoming/', views.UpcomingView.as_view(), name='upcoming'),
    path('new-post/', views.PostCreateView.as_view(), name='new_post'),
    path('post-detail/<pk>',views.PostDetailView.as_view(), name='post_detail'),
    path('post-delete/<pk>', views.PostDeleteView.as_view(), name="post_delete"),
]

templates/base.html
<!DOCTYPE html>
{% load tz %}
{% get_current_timezone as TIME_ZONE %}
<html lang="en">
<head>
    {% load static %}
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/mdb.css' %}" rel="stylesheet">
    <!-- Datatables -->
    <link href="{% static 'css/addons/datatables-select.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/addons/datatables-select2.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/addons/datatables.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/addons/datatables2.min.css' %}" rel="stylesheet">
    <!-- Calendar -->
    <link href="{% static 'css/addons/fullcalendar.min.css' %}" rel="stylesheet">
    {% block extrahead%}
    {% endblock %}
    {% block styles %}
    {% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="title" content="Servus Ticket">
    <meta name="description" content="Field Management Software for small to medium sized businesses. Easily track and manage technicians and service tickets daily.">
    <meta name="keywords" content="Field, Management, Software, Best, Technicians, Service, Tickets, Maintenance, Industry, HVAC, Electrician, Access Control, Plumbing">
    <meta name="robots" content="index, follow">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="language" content="English">

    <title>{{request.user.accountuser.account}}</title>
</head>
<body >
<style>
table.dataTable thead .sorting:after,
table.dataTable thead .sorting:before,
table.dataTable thead .sorting_asc:after,
table.dataTable thead .sorting_asc:before,
table.dataTable thead .sorting_asc_disabled:after,
table.dataTable thead .sorting_asc_disabled:before,
table.dataTable thead .sorting_desc:after,
table.dataTable thead .sorting_desc:before,
table.dataTable thead .sorting_desc_disabled:after,
table.dataTable thead .sorting_desc_disabled:before {
bottom: .5em;
}
</style>
<!-- SideNav slide-out button -->
<a href="#" data-activates="slide-out" class="btn blue-gradient p-3 button-collapse"><i
    class="fas fa-bars"></i></a>

<!-- Sidebar navigation -->
<div id="slide-out" class="side-nav2 side">
    <ul class="custom-scrollbar">
    <!-- Logo -->
        <li class='text-center'>
            <h4> Hi {{ user.accountuser.user.username}}!</h4>
            <small><b>{{ user.accountuser.account}}</b></small>
        </li>
        <!--/. Logo -->
        <!-- Side navigation links -->
        <li>
            <ul class="collapsible collapsible-accordion">
                <li>
                    <a class="collapsible-header waves-effect arrow-r"><i class="fas fa-chevron-right"></i>Dashboard<i class="fas fa-angle-down rotate-icon"></i>
                    </a>
                    <div class="collapsible-body">
                        <ul>
                            <li>
                                <a href="{% url 'today' %}" class="waves-effect">
                                   Today
                                   <span class="badge badge-light ml-2">
                                    {% if user.accountuser.role == 'Admin' %}
                                        {% if not todays_tickets_count %}
                                            0
                                        {% else %}
                                            {{ todays_tickets_count }}
                                        {% endif %}
                                    {% else %}
                                        {% if not tech_todays_ticket_count %}
                                            0
                                        {% else %}
                                            {{ tech_todays_tickets_count }}
                                        {% endif %}
                                    {% endif %}
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'schedule' %}" class="waves-effect">
                                   Schedule
                                </a>
                            </li>
                            {% if user.accountuser.role == 'Admin' %}
                            <li>
                                <a href="{% url 'upcoming:upcoming' %}" class="waves-effect">
                                   Upcoming 
                                </a>
                            </li>
                            {% else %}
                            {% endif %}
                        </ul>
                    </div>
                </li>
            </ul>
            <ul class="collapsible collapsible-accordion">
                <li>
                    <a class="collapsible-header waves-effect arrow-r"><i class="fas fa-chevron-right"></i> 
                        Tickets 
                        <i class="fas fa-angle-down rotate-icon"></i>
                    </a>
                    <div class="collapsible-body">
                        <ul>
                            <li>
                                <a href="{% url 'ticket_app:all_tickets' %}" class="waves-effect">
                                    All
                                    <span class="badge badge-light ml-2">
                                    {% if user.accountuser.role == 'Admin' %}
                                        {{ ticket_count }}
                                    {% else %}
                                        {% if not tech_ticket_count %}
                                            0
                                        {% else %}
                                            {{ tech_ticket_count }}
                                        {% endif %}
                                    {% endif %}
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'ticket_app:new_ticket' %}" class="waves-effect">
                                    New
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
            {% if user.accountuser.role == 'Admin' %}
            <ul class="collapsible collapsible-accordion">
                <li>
                    <a class="collapsible-header waves-effect arrow-r"><i class="fas fa-chevron-right"></i>Manage<i class="fas fa-angle-down rotate-icon"></i>
                    </a>
                    <div class="collapsible-body">
                        <ul>
                            <li>
                                <a href="{% url 'customer_app:companies' %}" class="waves-effect">
                                    Company
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'customer_app:customers' %}" class="waves-effect">
                                    Customer
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'customer_app:jobsites' %}" class="waves-effect">
                                    Jobsites
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'ticket_app:reports' %}" class="waves-effect">
                                    Time Reports
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
            <ul class="collapsible collapsible-accordion">
                <li>
                    <a class="collapsible-header waves-effect arrow-r"><i class="fas fa-chevron-right"></i>{{request.user.accountuser.account}} Settings<i class="fas fa-angle-down rotate-icon"></i>
                    </a>
                    <div class="collapsible-body">
                        <ul>
                            <li>
                                <a href="{% url 'accounts:users' %}" class="waves-effect">
                                    Users
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'ticket_app:ticket_type_list' %}" class="waves-effect">
                                    Ticket Type
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'ticket_app:serviceprovided_list' %}" class="waves-effect">
                                    Services 
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
            {% else %}
            {% endif %}
            <ul class="collapsible collapsible-accordion">
                <li>
                    <a class="collapsible-header waves-effect arrow-r"><i class="fas fa-chevron-right"></i>{{request.user.accountuser.account}} Account<i class="fas fa-angle-down rotate-icon"></i>
                    </a>
                    <div class="collapsible-body">
                        <ul>
                            <li>
                                <a href="{% url 'accounts:change_password' %}" class="waves-effect">
                                    Change Password
                                </a>
                            </li> 
                            <li>
                                <a href="{% url 'user_logout' %}" class="waves-effect">
                                    Logout
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
        </li>
        <!--/. Side navigation links -->
    </ul>
    <div class="sidenav-bg rgba-blue-strong">
    </div>
</div>
<!--/. Sidebar navigation -->

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    
    <!-- JQuery -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <!-- MDBootstrap Datatables  -->
    <script type="text/javascript" src="{% static 'js/addons/datatables2.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/addons/datatables-select2.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/addons/datatables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/addons/datatables-select.min.js' %}"></script>
    <!-- Calendar -->
    <script type="text/javascript" src="{% static 'js/addons/moment.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/addons/fullcalendar.min.js' %}"></script>
    
    
    <script>
        $(document).ready(function () {
            $('#ticket_list').DataTable({
            "order": [[ 0, "asc" ]]
            });
                
            $('.dataTables_length').addClass('bs-select');
            new WOW().init();
        });
    </script>
    <script>
        $(document).ready(function() {
            // SideNav Button Initialization
            $(".button-collapse").sideNav2();
            // SideNav Scrollbar Initialization
            var sideNavScrollbar = document.querySelector('.custom-scrollbar');
            var ps = new PerfectScrollbar(sideNavScrollbar);
            });
    </script>
    

    {% block scripts %}
    {% endblock %}
</body>
</html>

templates/calendar.html
{% extends 'dashboard.html' %}
{% block extrahead %}
{% load static %}
    <link href="{% static 'css/addons/fullcalendar.min.css' %}" rel="stylesheet">
{% endblock %}
{% block dash %}
<section>
  <div class="row">
    <div class="col-md-12">
      <div id="calendar"></div>
    </div>
  </div>
</section>
{% endblock %}

templates/dashboard.html
{% extends 'base.html' %}
{% block content %}
{% if user.accountuser.role == 'Admin' %}
<section class="p-5 z-depth-1 mb-5">
    <h3 class="text-center font-weight-bold mb-5"></h3>
    <div class="row d-flex justify-content-center">
        <div class="col-md-6 col-lg-3 mb-4 text-center">
            <h4 class="h1 font-weight-normal mb-3">
                <i class="fas fa-calendar-alt blue-text"></i>
                <span class="d-inline-block count-up" data-from="0" data-to="{{ todays_tickets_count }}" data-time="1500"></span>
            </h4>
            <p class="font-weight-normal text-muted">Scheduled for Today</p>
        </div>
        <div class="col-md-6 col-lg-3 mb-4 text-center">
            <h4 class="h1 font-weight-normal mb-3">
                <i class="fas fa-tools orange-text"></i>
                <span class="d-inline-block count1" data-from="0" data-to="{{ in_progress_count }}" data-time="1500"></span>
            </h4>
            <p class="font-weight-normal text-muted">In Progress Tickets</p>
        </div>
        <div class="col-md-6 col-lg-3 mb-4 text-center">
            <h4 class="h1 font-weight-normal mb-3">
                <i class="far fa-check-square green-text"></i>
                <span class="d-inline-block count2" data-from="0" data-to="{{ completed_today_tickets_count }}" data-time="1500"></span>
            </h4>
            <p class="font-weight-normal text-muted">Completed Today</p>
        </div>
    </div>
</section>
{% else %}
<section class="p-5 z-depth-1 mb-5">
    <h3 class="text-center font-weight-bold mb-5"></h3>
    <div class="row d-flex justify-content-center">
        <div class="col-md-6 col-lg-3 mb-4 text-center">
            <h4 class="h1 font-weight-normal mb-3">
                <i class="fas fa-calendar-alt blue-text"></i>
                <span class="d-inline-block count-up" data-from="0" data-to="{{ tech_todays_tickets_count }}" data-time="1500"></span>
            </h4>
            <p class="font-weight-normal text-muted">Scheduled for Today</p>
        </div>
        <div class="col-md-6 col-lg-3 mb-4 text-center">
            <h4 class="h1 font-weight-normal mb-3">
                <i class="far fa-check-square green-text"></i>
                <span class="d-inline-block count2" data-from="0" data-to="{{ tech_completed_today_tickets_count }}" data-time="1500"></span>
            </h4>
            <p class="font-weight-normal text-muted">Completed Today</p>
        </div>
    </div>
</section>
{% endif %}

{% block dash %}
{% endblock %}
{% block scripts %}
<script>
    (function ($){
        $.fn.counter = function() {
            const $this = $(this),
            numberFrom = parseInt($this.attr('data-from')),
            numberTo = parseInt($this.attr('data-to')),
            delta = numberTo - numberFrom,
            deltaPositive = delta > 0 ? 1 : 0,
            time = parseInt($this.attr('data-time')),
            changeTime = 10;
            
            let currentNumber = numberFrom,
            value = delta*changeTime/time;
            var interval1;
            const changeNumber = () => {
            currentNumber += value;
            //checks if currentNumber reached numberTo
            (deltaPositive && currentNumber >= numberTo) || (!deltaPositive &&currentNumber<= numberTo) ? currentNumber=numberTo : currentNumber;
            this.text(parseInt(currentNumber));
            currentNumber == numberTo ? clearInterval(interval1) : currentNumber;  
            }

            interval1 = setInterval(changeNumber,changeTime);
        }
        }(jQuery));

        $(document).ready(function(){

        $('.count-up').counter();
        $('.count1').counter();
        $('.count2').counter();
        $('.count3').counter();
        
        new WOW().init();
        
        setTimeout(function () {
            $('.count5').counter();
        }, 1500);
        });
</script>
<script>
$(document).ready(function(){
    var today = new Date();
        $('#calendar').fullCalendar({
        header: {
            left: 'prev,next today',
            center: 'title',
            right: 'listWeek,month'
        },
        defaultDate: today,
        defaultView: 'listWeek',
        navLinks: true,
        eventLimit: true,
      
        
        eventRender: function (eventObj, $el) {
            $el.popover({
                title: eventObj.title,
                content: eventObj.description,
                trigger: 'hover',
                placement: 'top',
                container: 'body'
            });
        },
        events: [
        {% if user.accountuser.role == 'Tech'%}
            {% for t in tech_tickets_calendar%}
            {
                title: "{{t.assigned}}",
                date:"{{t.schedule}}",
                description:"Ticket# {{t.ticket_number}}",
                url: "{% url 'ticket_app:ticket_detail' pk=t.ticket_number %}",
                allDay: true,
            },
            {% endfor %}
        {% endif %}
        {% if user.accountuser.role == 'Admin' %}
            {% for t in tickets %}
            {
                title: "{{t.assigned}} - {% if t.completed == True %} Completed {% elif t.start_job == True and t.completed == False %} In progress - Current time on the job is {{ t.start_time|timesince:t.end_time }} {% else %} {{ t.stop }} Stop {% endif %}",
                date:"{{t.schedule}}",
                description:"Ticket# {{t.ticket_number}} {% if t.completed == True %} Completed {% elif t.start_job == True and t.completed == False %} In progress - Current time on the job is {{ t.start_time|timesince:t.end_time }} {% else %} Incomplete {% endif %}",
                url: "{% url 'ticket_app:ticket_detail' pk=t.ticket_number %}",
                allDay: true,
            },
            
            {% endfor %}
        {% endif %}
        ],
        
    });     
});
</script>
{% endblock %}
{% endblock %}

templates/index.html
{% extends 'dashboard.html'%}

templates/today.html
{% extends 'dashboard.html'%}
{% block dash %}

<!-- Table with panel -->
<div class="card card-cascade narrower">
    <!--Card image-->
    <div class="view view-cascade gradient-card-header blue-gradient narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">
        <div>
            <div class="white-text mx-3">Todays Tickets</div>
        </div>
        <div class='justify-content-start'>
            <a href="{% url 'ticket_app:new_ticket' %}" type="button" class="btn btn-outline-white btn-sm px-2">
                <i class="fas fa-plus mt-0"></i> New Ticket
            </a>
        </div>
        
    </div>
    <!--/Card image-->
    <div class="px-5">
        <div class="table-wrapper">
            {% comment %} <h2 class='mb-3'>Basic example</h2> {% endcomment %}
            <table id="ticket_list" class="table table-hover table-sm table-responsive" width="100%">
                <thead>
                    <tr>
                        <th class="th-sm">Status
                        </th>
                        <th class="th-sm">Ticket
                        </th>
                        <th class="th-sm">Scheduled
                        </th>
                        <th class="th-sm">Customer
                        </th>
                        <th class="th-sm">Jobsite
                        </th>
                        <th class="th-sm">Scope
                        </th>
                        <th class="th-sm">Dept
                        </th>
                        <th class="th-sm">Call
                        </th>
                        <th class="th-sm">Tech
                        </th>
                        <th class="th-sm">Actions
                        </th>
                    </tr>
                </thead>
                <tbody>
                {% if user.accountuser.role == 'Admin' %}
                    {% for t in todays_tickets %}
                    {% if t.completed == True %}
                        <tr class="green lighten-4">
                            <td>Completed</td>
                    {% elif t.start_job == True and t.completed == False %}
                        <tr class="orange lighten-4">
                            <td>In Progress</td>
                    {% else %}
                        <tr class="blue lighten-4">
                            <td>Incomplete</td>
                    {% endif %}
                            <td>{{ t.ticket_number }}</td>
                            <td> {{ t.schedule }} </td>
                            <td>{{ t.t_customer}}</td>
                            <td>{{ t.t_jobsite|truncatechars:15 }}</td>
                            <td>{{ t.scope|truncatechars:20 }}</td>
                            <td>{{ t.department }}</td>
                            <td>{{ t.t_type }}</td>
                            <td>{{ t.assigned }}</td>
                            <td>
                                <a href="{% url 'ticket_app:ticket_detail' pk=t.ticket_number %}" type="button" class="btn btn-outline-blue btn-rounded btn-sm px-2">
                                    <i class="fas fa-eye lt mt-0"></i>
                                </a>
                                <a href="{% url 'ticket_app:ticket_update' pk=t.ticket_number %}" type="button" class="btn btn-outline-blue btn-rounded btn-sm px-2">
                                    <i class="fas fa-pencil-alt lt mt-0"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                    {% for t in tech_todays_tickets %}
                    {% if t.completed == True %}
                        <tr class="green lighten-4">
                            <td>Completed</td>
                    {% elif t.start_job == True and t.completed == False %}
                        <tr class="blue lighten-4">
                            <td>In Progress</td>
                    {% else %}
                        <tr class="grey lighten-2">
                            <td>Incomplete</td>
                    {% endif %}
                            <td>{{ t.ticket_number }}</td>
                            <td> {{ t.schedule }} </td>
                            <td>{{ t.t_customer}}</td>
                            <td>{{ t.t_jobsite }}</td>
                            <td>{{ t.scope|truncatechars:20 }}</td>
                            <td>{{ t.department }}</td>
                            <td>{{ t.t_type }}</td>
                            <td>{{ t.assigned }}</td>
                            <td>
                                <a href="{% url 'ticket_app:ticket_detail' pk=t.ticket_number %}" type="button" class="btn btn-outline-blue btn-rounded btn-sm px-2">
                                    <i class="fas fa-eye lt mt-0"></i>
                                </a>
                                <a href="{% url 'ticket_app:tech_ticket_update' pk=t.ticket_number %}" type="button" class="btn btn-outline-blue btn-rounded btn-sm px-2">
                                    <i class="fas fa-pencil-alt lt mt-0"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                {% endif %}   
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- Table with panel -->

{% endblock %}

templates/wizard.html
{% extends 'base.html' %}
{% block content %}

{% if not wizard %}
<h1>Tutorial</h1>
    <h5>
        Lets add a customer to get started!
        <a href="{% url 'customer:add_customer' %}" type="button" class="btn btn-outline-primary btn-rounded btn-sm px-2"><i class="fas fa-user-plus mt-0"></i> 
        New Customer
        </a>    
    </h5>
{% else %}
    <h5>
        Continue
        <a href="{% url 'today' %}" type="button" class="btn btn-outline-primary btn-rounded btn-sm px-2"><i class="fas fa-user-plus mt-0"></i> 
        </a>    
    </h5>
{% endif %}


{% endblock %}